condense_wildcard_suffixes = true
enum_discrim_align_threshold = 30
format_strings = true
group_imports = "StdExternalCrate"
imports_indent = "Visual"
overflow_delimited_expr = true
reorder_impl_items = true
struct_field_align_threshold = 30
unstable_features = true
use_field_init_shorthand = true
where_single_line = true
