attr_fn_like_width = 90
condense_wildcard_suffixes = true
enum_discrim_align_threshold = 30
format_strings = true
group_imports = "StdExternalCrate"
imports_indent = "Visual"
max_width = 110
overflow_delimited_expr = true
reorder_impl_items = true
single_line_if_else_max_width = 80
struct_field_align_threshold = 30
struct_lit_width = 40
unstable_features = true
use_field_init_shorthand = true
where_single_line = true
