name: Haskell CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ["./2020/haskell"]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1.4
        with:
          ghc-version: "8.10.4"
          stack-version: "2.7.1"

      - uses: actions/cache@v2.1.3
        name: Cache ~/.stack
        with:
          path: ${{ matrix.dir }}/.stack
          key: ${{ env.cache-name }}-stack-${{ hashFiles('**/package.yaml') }}

      - name: Install dependencies
        run: stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --only-dependencies
        working-directory: ${{ matrix.dir }}

      - name: Build
        run: stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks
        working-directory: ${{ matrix.dir }}

      - name: Test
        run: stack test --system-ghc
        working-directory: ${{ matrix.dir }}
