name: Haskell CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ["./2020/haskell"]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.3'
        cabal-version: '3.2'

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ${{ matrix.dir }}/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
      working-directory: ${{ matrix.dir }}
      
    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all
      working-directory: ${{ matrix.dir }}
      
    - name: Run tests
      run: cabal test all
      working-directory: ${{ matrix.dir }}
