name: Python Package using Conda

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      working-directory: python/

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          conda config --add channels conda-forge 
          conda env update --file environment.yml --name base
        working-directory: ${{ env.working-directory }}

      - name: Run Black
        run: |
          conda install black
          black --check y2020/
        working-directory: ${{ env.working-directory }}

      - name: Run Mypy
        run: |
          conda install mypy
          mypy y2020/
        working-directory: ${{ env.working-directory }}

      - name: Test with pytest
        run: |
          conda install pytest
          pip install pytest-xdist[psutil]
          # pytest 2019/python
          pytest y2020
        working-directory: ${{ env.working-directory }}
