name: Python Package using Conda

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          conda config --add channels conda-forge 
          conda env update --file python/environment.yml --name base
      - name: Test with pytest
        run: |
          conda install pytest
          pip install pytest-xdist[psutil]
          # pytest 2019/python
          pytest python/y2020
