name: Rust

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 1"
env:
  CARGO_TERM_COLOR: always

jobs:
  test_2019:
    runs-on: ubuntu-latest
    env:
      working-directory: ./2019/rust
    steps:
      - uses: actions/checkout@v2
      - name: Build 2019
        run: cargo build --verbose
        working-directory: ${{env.working-directory}}
      - name: Test 2019
        run: cargo test --verbose
        working-directory: ${{env.working-directory}}

  test_2020:
    runs-on: ubuntu-latest
    env:
      working-directory: ./2020/rust
    steps:
      - uses: actions/checkout@v2
      - name: Build 2020
        run: cargo build --verbose
        working-directory: ${{env.working-directory}}
      - name: Test 2020
        run: cargo test --verbose
        working-directory: ${{env.working-directory}}
