name: Rust

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 1"
env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ["./2019/rust", "./2020/rust"]

    steps:
      - uses: actions/checkout@v2
      - name: ⚡ Cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ matrix.dir }}/.cargo/registry
            ${{ matrix.dir }}/.cargo/git
            ${{ matrix.dir }}/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('${{ matrix.dir }}/Cargo.lock') }}
      - name: Build
        run: cargo build --verbose
        working-directory: ${{ matrix.dir }}
      - name: Test
        run: cargo test --verbose
        working-directory: ${{ matrix.dir }}
