name: Rust

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 1"
env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ["./2019/rust", "./2020/rust"]

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
        working-directory: ${{ matrix.dir }}
      - name: Test
        run: cargo test --verbose
        working-directory: ${{ matrix.dir }}
